server:
  port: 8082
spring:
  application:
    name: order-service2
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_demo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      server-addr: localhost:8848
mybatis-plus:
  global-config:
    db-config:
      insert-strategy: not_null
      update-strategy: not_null
      id-type: auto
logging:
  level:
    org.springframework.cloud.alibaba.seata.web: debug
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
seata:
  # TC服务注册中心的配置，微服务根据这些信息去注册中心获取tc服务地址
  registry:
    # 参考tc服务自己的registry.conf中的配置
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      # 空字符串就是默认值public
      namespace: ""
      group: DEFAULT_GROUP
      # tc服务在nacos中的服务名称
      application: seata-tc-server
      cluster: SH
  # 事务组，根据这个获取tc服务的cluster名称
  tx-service-group: seata-demo
  service:
    # 事务组与TC服务cluster的映射关系
    vgroup-mapping:
      seata-demo: SH
  # 开启数据源代理的XA模式
  data-source-proxy-mode: XA